language: python
python:
    - "3.5"

# Commands to install dependencies
install:
    - pip3 install -e .

# Commands to run tests
script:
    # Test the simulator
    - xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py

    # Test RL code quickly
    - cd pytorch-a2c-ppo-acktr && time python3 main.py --no-cuda --algo ppo --log-interval 1 --num-frames 500 --num-processes 1 --num-steps 80 --lr 0.00005 --env-name MiniWorld-Hallway-v0
