language: python
python:
    - "3.5"

# command to install dependencies
install:
    - pip3 install -e .

# command to run tests
script:
    - xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py
